#!/bin/bash
mkdir -p ~/.vim/bundle/
mkdir -p ~/.vim/files/info/
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall
