#!/bin/bash
alias bat="upower -i /org/freedesktop/UPower/devices/battery_BAT0"

# Don't print the bc(1) welcome message
alias bc='bc -q'

# Use a unified format for diff(1) by default
alias diff='diff -u'

# Don't print the GDB copyright message on every invocation
alias gdb='gdb -q'

