# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/simkim/.zshrc'

autoload -Uz compinit
compinit
alias ls="ls --color"
export PATH="/home/simkim/.local/bin:$PATH"
# End of lines added by compinstall

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
